version: '3.7'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: news

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
#  cats-api:
#    build: .
#    ports:
#      - 8082:8082
#    depends_on:
#      - db
#    environment:
#      DB_URL: jdbc:mysql://db:3306/cats
#      DB_PASS: root123
#      DB_USER: root